### ISSUE TITLE
[META] API Routes

### ISSUE THREAD

**Issue by arnopensource** [abc3354/CODEV-back#21]
List of all routes

- /auth
  - [x] GET /auth/check 
  - [x] POST /auth/login
  - [x] POST /auth/signup
  - [x] /nfc
    - [x] POST /auth/nfc/login
    - [x] PUT /auth/nfc/{id}
- /rooms 
  - [x] GET /rooms/empty
    - [ ] #19 
- /bookings
  - [x] POST /bookings #22 
    - [x] #31
  - [x] #41 
- /users #24 
  - [ ] GET /users
  - [ ] GET /users/{id}
  - [x] #30
  - [x] #32
- /friends
  - [x] GET /friends
  - [x] #34
  - [x] #37
  - [x] #35
  - [x] #33
  - [x] #47 
- /events #36
  - [x] POST /events
  - [x] GET /events
  - [x] PUT /events/{id}
  - [x] DELETE /events/{id}
  - [x] POST /events/invites - invite (admin)
  - [x] GET /events/invites - see my invites
  - [x] PUT /events/invites/{id} - accept/decline invite - **the id is an event id !**
  - [x] DELETE /events/invites - cancel invite (admin)
  - [x] GET /events/{id}/invites - see pending invites for the event
  - [x] GET /events/{id}/members - get event members
  - [x] DELETE /events/{id}/members - remove a member (admin)
  - [x] DELETE /events/{id}/me - quit event
  - [x] PUT /events/{id}/admins - share admin rights with a member (admin)
